### ISSUE TITLE
Config option detailsInExplorer showing unexpected behavior

### ISSUE THREAD

**Issue by b4skyx** [LeonardSSH/coc-discord-rpc#10]
Configuration:
  ``"rpc.detailsInExplorer": "Workspace: {workspace}",``
Expected Behavior:
   `Workspace: workspaceName` in explorer of rich presence
Behavior Found:
   Defaults to WorksnameName and Problems found

Issue:   
The `rpc.detailsInExplorer` picks the default configuration ignoring the config string passed.   
When the `rpc.showProblems` is used, it ignores the problems, but still doesn't shows the configured string pattern.

Environment:
CocInfo:
```
vim version: NVIM v0.4.4
node version: v15.5.1
coc.nvim version: 0.0.80-a112e6621b
coc.nvim directory: /home/abi/.config/nvim/plugged/coc.nvim
term: st-256color
platform: linux
```
coc-discord-rpc: v3.0,9

**Comment by LeonardSSH** [comment]
It will be fixed in the next version, which will be in about 1 week. Due to the fact that I want to rewrite the entire extension and use newer technologies.

😊

**Comment by b4skyx** [comment]
Thanks for the good work! The issue is open just incase~

**Comment by LeonardSSH** [comment]
@b4skyx Can you upgrade the extension to the new version 4.0.0? I want to know if there are any problems. Thanks!

**Comment by b4skyx** [comment]
I did check the settings after update, the variables seem to be working fine, however there is this behavior.
Whenever you open a file, the status defaults to idling mode unless you switch/open some other buffer.

Example:
```
command: nvim
behavior: Idling

command: nvim test.txt
behavior: Idling

Action: Move around buffers/open new one
behavior: viewing/editing
```

This wasn't the case before extension update.

**Comment by LeonardSSH** [comment]
Of course, because it is now event-based, if they are not called, the RPC will not be updated.

**Comment by LeonardSSH** [comment]
Actually, I can make to display from the first one what you are editing/viewing. 🤔🤔

Possibly in a future update it will be added, I'm not sure.

Have you encountered any other problems with the extension?

**Comment by b4skyx** [comment]
Ah I see, wasn't sure if it was intentional or a bug. But yes, things did change from the last version so thought of letting you know.

About any other issues, nope, things are working as expected. Thanks for the good work :sparkles: 
Might close this issue, since the original one is solved.
