### ISSUE TITLE
Doesn't work on MacOS

### ISSUE THREAD

**Issue by K-NRS** [LeonardSSH/coc-discord-rpc#15]
The extension works properly on my Linux devices. However, it could not connect to Discord RPC on MacOS.
  
  Need a permission or setting? Or, is it a problem about the extension?
  I've checked it in privacy settings but no missing or incorrect thing appears.

![image](https://user-images.githubusercontent.com/20605111/106657156-bc212080-65ac-11eb-965c-2392ef54ddd2.png)

**Comment by Vaansh** [comment]
If you haven't figured it out, here is what worked for me:

1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`

Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.

**Comment by K-NRS** [comment]
It worked for me too, thank you. Should be fixed in the project also.

**Comment by LeonardSSH** [comment]
@Vaansh **znz8yyl55ls27thh9l56x6rr0000gn** is this value static? If so, then I can modify the RPC library to detect whether it is running on macOS or not.

**Comment by K-NRS** [comment]
> @Vaansh **znz8yyl55ls27thh9l56x6rr0000gn** is this value static? If so, then I can modify the RPC library to detect whether it is running on macOS or not.

The value is not static. Mine was different.

**Comment by Vaansh** [comment]
@LeonardSSH No, I do not think it is static since it’s different from someone’s path in [another](https://github.com/LeonardSSH/coc-discord-rpc/issues/7#issuecomment-770571226) issue.

**Comment by LeonardSSH** [comment]
Hmm, then, there is another solution, we could execute `find /private/var/folders -name "*discord-ipc*" 2> /dev/null` using **child_process**, and that's how we find the path where the **discord-ipc** is. But I'm going to need one of you for tests if you want to help me. 😊

**Comment by LeonardSSH** [comment]
It seems that there is already a PR with a solution to this problem: https://github.com/discordjs/RPC/pull/113

**Comment by Giotje** [comment]
> If you haven't figured it out, here is what worked for me:
> 
>     1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
>        in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> 
>     2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> 
>     3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> 
> 
> Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.

i love u man it works
