### ISSUE TITLE
Feature request: add a vim lang icon.

### ISSUE THREAD

**Issue by KarlWithK** [LeonardSSH/coc-discord-rpc#16]
So, would it be possible that when editing a file with a `.vim` extension or your `.vimrc` to display a Vim logo/icon?

**Comment by LeonardSSH** [comment]
Sure. Will be in the next update, in a few days (or even today if I manage to finish configuring my environment).

👌

**Comment by LeonardSSH** [comment]
Will be valid in the next version that will be published in few moments.
