### ISSUE TITLE
Disabling startup message

### ISSUE THREAD

**Issue by kamui-7** [LeonardSSH/coc-discord-rpc#17]
Every time I start nvim, this message shows up
![image](https://user-images.githubusercontent.com/65237048/108288582-72ab0680-7152-11eb-9411-42c8b28fbd3b.png)

Is there a way I can disable this?

**Comment by LeonardSSH** [comment]
There was a setting, but I removed it. I can add it in the next update as a patch, if you want. ☺️

**Comment by vitiko98** [comment]
@LeonardSSH Any news on this? It would be very useful.

**Comment by LeonardSSH** [comment]
@vitiko98 soon™

**Comment by Ngomana** [comment]
I was unable to connect I installed it and when I opened up NeoVim it printed out: `[coc.nvim] RPC: Could not connect`
I also tried to enable with `[coc.nvim]: Error on notification "runCommand": Could not connect`
And reconnect as well `[coc.nvim] RPC: Could not connect `

**Comment by LeonardSSH** [comment]
The setting will be valid at the next update. In about a few days (or maybe a few hours).

**Comment by LeonardSSH** [comment]
@Nin-10-doer set `rpc.suppressNotifications` to `false.
```json
"rpc.suppressNotifications": false
```

The condition in the code should have been different, but I wasn't paying attention.

**Comment by Nin-10-doer** [comment]
> @Nin-10-doer set `rpc.suppressNotifications` to `false`.
> ```json
> "rpc.suppressNotifications": false
> ```
> 
> The condition in the code should have been different, but I wasn't paying attention.

Oh thanks, yeah I saw that option but the default true in the docs confused me so I didn't think it was that option the one I was looking for.

**Comment by LeonardSSH** [comment]
`suppressNotifications` should remove all messages that appear in nvim starting page, at least this is how it is implemented and tested (at the time of implementation)

**Comment by Nin-10-doer** [comment]
My bad, my starting page disappears for whatever reason and I thought it was because RPC because it disappears at the same time the notification appears, but I just removed discord rpc and the starting page still disappears after a few seconds.

Thank you anyway, I'm gonna look which plugin or setting is doing this
