### ISSUE TITLE
Disable warning if it couldn't connect

### ISSUE THREAD

**Issue by scrouthtv** [LeonardSSH/coc-discord-rpc#19]
Hello,

I like this problem, however I don't have discord open all the time on my pc. So whenever I open vim I get this bright error:
![image](https://user-images.githubusercontent.com/23227405/110204003-1f82c480-7e71-11eb-874d-c9cb0dec2f31.png)
Which I don't really care about as it works as long as I have discord open.

Is there any option to disable this warning? 

Thanks in advance.

**Comment by LeonardSSH** [comment]
Hello, the extension doesn't have a special setting to disable this error, but you can use the `:CocCommand rpc.disable` command to disable the entire extension, and when you want to display RPC, use the `:CocCommand rpc.enable` command for now.

Maybe in the future I can add a special setting for that.

**Comment by scrouthtv** [comment]
Thank you very much.
