### ISSUE TITLE
Live Linting shows editing Text File not the file it self on discord ? 

### ISSUE THREAD

**Issue by vsedov** [LeonardSSH/coc-discord-rpc#20]
A slight issue occurred recently though im not sure why . Is if you have ALE Live linting enabled , discord states that you are editing a text file , though im not all to sure why , i did try messing around to no eval , i had to disable live linting for the time, any ideas ? 
![image](https://user-images.githubusercontent.com/28804392/110216309-50c9b780-7ea6-11eb-8ce6-b8b492531b9b.png)

though this should just be a python file and the only two buffers open is the quick fix list  and the file it self .

Il be happy to help if i can that is : ) just let me know .

**Comment by LeonardSSH** [comment]
The extension is written in such a way that it is updated according to the events that happen while you are in NeoVim. Probably when ALE Live linting is enabled, it opens a new buffer, which triggers an event that updates the RPC. This is the only explanation I can give you at the moment. 

Can you tell me the steps you take to achieve this? I have never used ALE Live linting, and I would like to know how it works.

**Comment by vsedov** [comment]
yeah sure - i mean i love this plugin so i don't mind if it can't be fixed : ) 
And your probably right , what it does is , while you type you have another buffer , which constantly gets updated such that say you have a syntax error , it will notify you in the quick fix list  .  Almost immediately . 
Once you install ale , and add these settings into your init.vim . Hopefully you might be able to replicate it ? 

```
let g:ale_list_window_size =  4
let g:ale_sign_column_always = 1
let g:ale_open_list = 1
let g:ale_linters = {
  \   'python': ['black','pylint''], "Some python linter of your choice here 
\}
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_keep_list_window_open = 1
let g:ale_list_vertical = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
```

out of curiosity is there a way that discord rpc can avoid certain types of buffers or file types  ? 

for example 
the response from 
``` 
:echo &filetype 
```
is qf - for the quick fix window and rpc could just ignore that file type ? , though im not sure if that would work if im honest >.< 

Hope this helps a bit .

**Comment by LeonardSSH** [comment]
> out of curiosity is there a way that discord rpc can avoid certain types of buffers or file types ?

Absolutely

If you say that `:echo &filetype` is `qf`, I can put an IF to return the current RPC state, and ignore the new buffer from ALE Live linting.

Can you add me on discord `Leonard#6666`, for help me with the tests?

**Comment by vsedov** [comment]
Yep will do, cheers .

**Comment by LeonardSSH** [comment]
Can you tell me your discord id? I've 999+ friend requests 😂😂

**Comment by vsedov** [comment]
Oh my , sorry about that : AloofPolo#9428
