### ISSUE TITLE
Unable to connect to discord after installation

### ISSUE THREAD

**Issue by Ngomana** [LeonardSSH/coc-discord-rpc#21]
I was unable to connect I installed it and when I opened up NeoVim it printed out: `[coc.nvim] RPC: Could not connect`
I also tried to enable with `[coc.nvim]: Error on notification "runCommand": Could not connect`
And reconnect as well `[coc.nvim] RPC: Could not connect `

**Comment by AlexWillCode** [comment]
I just installed coc-discord-rpc for the first time and can reproduce.

**Comment by Ngomana** [comment]
So you were able to connect to discord?

**Comment by Ngomana** [comment]
> I just installed coc-discord-rpc for the first time and can reproduce this bug.

So you were able to connect to discord?

**Comment by AlexWillCode** [comment]
I wasn't able to connect to Discord.

**Comment by AakashSharma7269** [comment]
I get the same error stating: `[coc.nvim] RPC: could not connect`

**Comment by Ngomana** [comment]
> I wasn't able to connect to Discord.

use `coc-discord-presence`

**Comment by tomadojuice** [comment]
Same Error for me... I'm on MacOS maybe that could be a problem.

**Comment by ShinteiMai** [comment]
Refer to [this](https://github.com/LeonardSSH/coc-discord-rpc/issues/15) issue that happened before.

It seems that this is an issue specific to macOS. Luckily, there is a fix posted by @Vaansh

> If you haven't figured it out, here is what worked for me:
> 
> 1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
>    in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> 2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> 3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> 
> Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.

**Comment by Ngomana** [comment]
> Refer to [this](https://github.com/LeonardSSH/coc-discord-rpc/issues/15) issue that happened before.
> 
> It seems that this is an issue specific to macOS. Luckily, there is a fix posted by @Vaansh
> 
> > If you haven't figured it out, here is what worked for me:
> > 
> > 1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
> >    in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> > 2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> > 3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> > 
> > Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.

Still doesn't work

**Comment by slothonmeth1** [comment]
I am able to reproduce this on 5.10.36-2-MANJARO

**Comment by LeonardSSH** [comment]
Please update the extension and let me know if the problem is solved.

**Comment by Ngomana** [comment]
This is what I'm getting. 
```[coc.nvim]: Error on notification "runCommand": Cannot read property 'write' of null```

**Comment by Ngomana** [comment]
> Please update the extension and let me know if the problem is solved.

**Comment by LeonardSSH** [comment]
Can you tell me what source you installed the discord from?

**Comment by Ngomana** [comment]
> Can you tell me what source you installed the discord from?

`CocInstall coc-discord-rpc`

**Comment by stephfh** [comment]
Also getting that error with the most recent release of the package. 

> [coc.nvim] Error on activate extension coc-discord-rpc: Cannot read property 'write' of null

Versions: 
> Big Sur 11.5
> nvim 0.5
> Discord: 0.0.263

> Can you tell me what source you installed the discord from?

Standard `.dmg` from the website, not via brew or any other package manager.

**Comment by LeonardSSH** [comment]
If you are using VSCode, please test the https://github.com/LeonardSSH/vscord extension, it is made with the same discord rpc. Please let me know if it works.

**Comment by stephfh** [comment]
Just installed your extension for VSCode. Yes, that one is able to connect to Discord, the second it finished installing the extension.

**Comment by LeonardSSH** [comment]
@stephfh please see https://github.com/LeonardSSH/coc-discord-rpc/issues/45 https://github.com/LeonardSSH/coc-discord-rpc/issues/18  https://github.com/LeonardSSH/coc-discord-rpc/issues/15

**Comment by Ngomana** [comment]
unfortunately I only use Neo vim

**Comment by lewisblackburn** [comment]
> > Refer to [this](https://github.com/LeonardSSH/coc-discord-rpc/issues/15) issue that happened before.
> > It seems that this is an issue specific to macOS. Luckily, there is a fix posted by @Vaansh
> > > If you haven't figured it out, here is what worked for me:
> > > 
> > > 1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
> > >    in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> > > 2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> > > 3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> > > 
> > > Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.
> 
> Still doesn't work

![Screenshot 2021-08-30 at 15 34 38](https://user-images.githubusercontent.com/51877955/131356258-964f0390-ebd0-4f29-8044-344228c52a3a.png)

Does anyone know why I don't have a lib folder?

**Comment by LeonardSSH** [comment]
@lewisblackburn 'Cause in the new version, the lib folder has been changed to dist. I forgot to mention this in the release. 😅

**Comment by Ngomana** [comment]
![Screenshot 2021-08-30 at 20 12 04](https://user-images.githubusercontent.com/61317733/131385044-f24d3b97-500e-4430-a2e6-ddd20e9ad11b.png)

**Comment by lewisblackburn** [comment]
> @lewisblackburn 'Cause in the new version, the lib folder has been changed to dist. I forgot to mention this in the release. 😅

Thanks! 😄

**Comment by Ngomana** [comment]
> > @lewisblackburn 'Cause in the new version, the lib folder has been changed to dist. I forgot to mention this in the release. 😅
> 
> Thanks! 😄

did it work?

**Comment by lewisblackburn** [comment]
unfortunatley not

**Comment by RayCurse** [comment]
> Refer to [this](https://github.com/LeonardSSH/coc-discord-rpc/issues/15) issue that happened before.
> 
> It seems that this is an issue specific to macOS. Luckily, there is a fix posted by @Vaansh
> 
> > If you haven't figured it out, here is what worked for me:
> > 
> > 1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
> >    in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> > 2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> > 3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> > 
> > Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.

This fix worked for me but the index.js file was different. I did a ctrl-f for "discord-ipc" to find the return statement that was mentioned, and following the steps from there fixed the issue for me.

**Comment by Ngomana** [comment]
it worked!!! 
could some please submit a pull request

**Comment by carandev** [comment]
> > Refer to [this](https://github.com/LeonardSSH/coc-discord-rpc/issues/15) issue that happened before.
> > It seems that this is an issue specific to macOS. Luckily, there is a fix posted by @Vaansh
> > > If you haven't figured it out, here is what worked for me:
> > > 
> > > 1. `$ find /private/var/folders -name "*discord-ipc*" 2> /dev/null`
> > >    in my case it returned: `/private/var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-0`
> > > 2. Go into `/.config/coc/extensions/node_modules/coc-discord-rpc/lib` and open `index.js`.
> > > 3. Change line 3046 from `return ${prefix.replace(/\/$/, '')}/discord-ipc-${id};` to `return /var/folders/g3/znz8yyl55ls27thh9l56x6rr0000gn/T/discord-ipc-${id};`
> > > 
> > > Configure 3. to return your discord pic path accordingly, and put both the returns in backticks.
> 
> This fix worked for me but the index.js file was different. I did a ctrl-f for "discord-ipc" to find the return statement that was mentioned, and following the steps from there fixed the issue for me.

Hi, I have the same error but with Debian in WSL2

**Comment by LeonardSSH** [comment]
@carandev for WSL, try: https://gist.github.com/mousebyte/af45cbecaf0028ea78d0c882c477644a
