### ISSUE TITLE
Rich presence not properly stopping

### ISSUE THREAD

**Issue by Vendicated** [LeonardSSH/coc-discord-rpc#23]
Every once in a while the rich presence will get stuck and not properly stop when exiting nvim and show you as idling until you kill the nvim background process

I am not sure what's causing this and it doesnt seem to be reproducable :/

**Comment by LeonardSSH** [comment]
Fixed. https://github.com/LeonardSSH/coc-discord-rpc/pull/38#issuecomment-854910348
