### ISSUE TITLE
rpc.idleText doesn't work?

### ISSUE THREAD

**Issue by Magicrafter13** [LeonardSSH/coc-discord-rpc#24]
I wanted to have a sarcastic little message for when I'm idle, so I gave it a value, and also set `rpc.checkIdle` to 10 seconds so I could easily see if the change worked. I unfocused my terminal, switched to Discord, waited 10 seconds... nothing. Waited a bit longer... nothing. Tried to find a coc command that could help me figure out the issue but I didn't find anything. Didn't see anything important in `:CocOpenLog` either.

Here's my coc-settings.json. Pretty bare, I know.
```jsonc
{
	// 0_coc
	"coc.preferences.extensionUpdateCheck": "daily",

	// 1_java
	"java.clean.workspace": true,
	"java.completion.enabled": true,
	"java.codeGeneration.generateComments": true,

	// 2_discord
	"rpc.workspaceElapsedTime": true,
	"rpc.checkIdle": 10,
	"rpc.idleText": "Zᴢz",

	"": ""
}
```
I originally tried a much longer string by the way, but after it didn't work I thought maybe there was a character limit so I set it to the Zzz, but obviously it still didn't work.
![rpc](https://user-images.githubusercontent.com/29127566/117564294-47a0c680-b060-11eb-98c9-ddb390eee817.png)

**Comment by LeonardSSH** [comment]
I've to rewrite the whole "idle" a little bit, to make something more optimal and work properly. If you have any ideas on how I can do this, feel free to contribute. #38

**Comment by LeonardSSH** [comment]
Fixed. Available *soonTM* - https://github.com/LeonardSSH/coc-discord-rpc/pull/38#issuecomment-854910348
