### ISSUE TITLE
How would I get rid of the Coc dependency? 

### ISSUE THREAD

**Issue by KarlWithK** [LeonardSSH/coc-discord-rpc#25]
If I wanted to fork this and get rid of Coc, how would I accomplish this? This would really help out if I use nvim's builtlin lsp, but still use this plugin.

**Comment by whisperity** [comment]
Search for `coc` in the code. I guess the biggest issue is that this plugin sets up commands that will be available from the `CocCommand` interface. It also uses Coc's interface to grab information about your open file, and the entire plugin is written in TypeScript, which isn't natively executed by (n)Vim AFAIK. You'd need to rewrite the whole thing in Lua (for nvim) or Vimscript (for stock Vim)...

But there are several other Discord RPC plugins for Vim that do not require coc, so you're simply better off just configuring up those for your liking.

**Comment by LeonardSSH** [comment]
I think you got the best answer.
