### ISSUE TITLE
C header files shown as manifest files?

### ISSUE THREAD

**Issue by MonliH** [LeonardSSH/coc-discord-rpc#26]
When editing a file named `lol_runtime.h`, the rich presence indicator shows the file as a MANIFEST file:

![image](https://user-images.githubusercontent.com/30177086/119264161-f6401d80-bbaf-11eb-8aaf-08490f7d3121.png)

 `.h` (in a programming context) usually refers to a C header file, which isn't really a manifest. I would put a `.h` file under C, given that `.hpp` files are put under c++: [https://github.com/LeonardSSH/coc-discord-rpc/blob/main/src/icons.json#L200](https://github.com/LeonardSSH/coc-discord-rpc/blob/main/src/icons.json#L200).

I could open a PR if needed :)

**Comment by LeonardSSH** [comment]
Fixed, will be valid at the next update. In about a few days (or maybe a few hours).
