### ISSUE TITLE
Extension not parsing my options

### ISSUE THREAD

**Issue by tomato4** [LeonardSSH/coc-discord-rpc#50]
Extension is not parsing eg. {workspace} or {filename}. It just left it as it is.

There is how it looks like
![image](https://user-images.githubusercontent.com/26723812/124943444-c8525380-e00c-11eb-93e4-3c5fda57ee37.png)

There is my coc config
```json
{
    "rpc.checkIdle": false,
    "rpc.detailsViewing": "In {workspace}",
    "rpc.detailsEditing": "In {workspace}",
    "rpc.lowerDetailsEditing": "{filename}",
    "rpc.lowerDetailsViewing": "{filename}"
}
```

Feel free to ask for additional informations.

**Comment by LeonardSSH** [comment]
```
{workspace} should be {workspace_folder}
{filename} should be {file_name}
```

Sorry, I forgot to modify the [Wiki](https://github.com/LeonardSSH/coc-discord-rpc/wiki/Using-the-configuration-file). 😅

**Comment by tomato4** [comment]
That solved the issue. Thanks!
