### ISSUE TITLE
cannot read property 'write' of null

### ISSUE THREAD

**Issue by kekidev** [leonardssh/coc-discord-rpc#56]
im using m1 mac

this is my init.vim right now
<img width="415" alt="Screen Shot 2021-09-02 at 10 04 57 PM" src="https://user-images.githubusercontent.com/72121955/131848581-c7d54ba5-c3ce-47f4-b6cc-76c424132193.png">

and the error is
```[coc.nvim] Error on activate extension coc-discord-rpc: Cannot read property 'write' of null```

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/coc-discord-rpc/issues/21#issuecomment-910384599

**Comment by kekidev** [comment]
> [#21 (comment)](https://github.com/LeonardSSH/coc-discord-rpc/issues/21#issuecomment-910384599)

<img width="948" alt="Screen Shot 2021-09-03 at 12 02 43 AM" src="https://user-images.githubusercontent.com/72121955/131868067-523bfb13-c411-4f7a-bca9-74d6dd499bab.png">
i couldn't find that and its all encrypted

**Comment by RayCurse** [comment]
It's unreadable, but you can spot the beginning of the return statement in question before the second occurrence of "discord-ipc."

**Comment by misterbug5** [comment]
I'm getting the same issue in Ubuntu 20.04, I thought that it was a snap thing but after reinstalling discord the error persist

**Comment by excalios** [comment]
I have the same issue I believe with a kind of different message
![image](https://user-images.githubusercontent.com/42968441/140502608-f9bb80da-2096-4608-8fbe-010a43269077.png)
I tried finding out looking at the link that you refer about the ipc with the mac and thought maybe my discord have a separate package for ipc since I'm on arch. And so far I don't think this is the case. Not really sure yet why this happens

**Comment by excalios** [comment]
> I have the same issue I believe with a kind of different message ![image](https://user-images.githubusercontent.com/42968441/140502608-f9bb80da-2096-4608-8fbe-010a43269077.png) I tried finding out looking at the link that you refer about the ipc with the mac and thought maybe my discord have a separate package for ipc since I'm on arch. And so far I don't think this is the case. Not really sure yet why this happens

A follow up reply it now works again not really sure why since I didn't do anything

**Comment by KarlWithK** [comment]
Not working :(. Works well on linux, but not on mac currently

**Comment by LeonardSSH** [comment]
@KarlWithK hey, on mac I know there are problems, there's nothing I can do about it, it's up to discord-rpc to fix it, there's also an open PR for this purpose.

**Comment by booleans-oss** [comment]
> @KarlWithK hey, on mac I know there are problems, there's nothing I can do about it, it's up to discord-rpc to fix it, there's also an open PR for this purpose.

Any updates ? I see there are no open PRs anymore

**Comment by xhayper** [comment]
This seems to be nvim/coc issue NOT disord-rpc-issue.
