### ISSUE TITLE
Cannot read properties of null reading "write" 

### ISSUE THREAD

**Issue by JotaroKujo0525** [leonardssh/coc-discord-rpc#59]
Been coding on nvim and I installed this Plugin until encountered this error

![Screenshot_20211119_165633](https://user-images.githubusercontent.com/77835007/142594647-694b394f-40ee-4acd-acc8-a0af154a04c4.jpg)

**Comment by Nuddel69** [comment]
I'm having the same issue. Did you ever figure it out?

**Comment by LeonardSSH** [comment]
This error occurs when the rpc doesn't find the discord client (it is not started or rpc doesn't have permissions).

**Comment by Magicrafter13** [comment]
I've been getting this issue lately - but it only seems to happen when I use my window manager (Awesome) instead of my usual desktop environment (KDE). So it's probably not an issue with the plugin (for me), but does anyone know what might cause this in my situation?

**Comment by AucaCoyan** [comment]
I'm getting the same error. Is there any configuration I need to setup to make it work?

**Comment by Srijandev** [comment]
@LeonardSSH Uhm, facing the same bizzare issue? Would you mind helping us?

**Comment by Srijandev** [comment]
Seems like all issues are dead.

**Comment by ken-soares** [comment]
can't get this to work either

**Comment by Srijandev** [comment]
sadge :(

**Comment by b3z** [comment]
same here

**Comment by Srijandev** [comment]
I see, Maintainer aren't responding 😐

**Comment by Srijandev** [comment]
@leonardssh

**Comment by Paxxous** [comment]
I have the same issue. As well as:
`[coc.nvim] RPC: TypeError: e.forEach is not a function`

**Comment by TudbuT** [comment]
Same thing is happening to me

**Comment by TudbuT** [comment]
@leonardssh this issue is 3/4 of a year old and fatal.

**Comment by leonardssh** [comment]
@TudbuT I know about this issue, I tried to solve it, but to no avail. At the moment I don't have the time and environment to start try solving it again.

**Comment by Srijandev** [comment]
Uh, this sucks! :(

**Comment by xhayper** [comment]
Can you guys try installing `leonardssh/coc-discord-rpc#build-dev` version of the extenstion? It should fix this bug, if it did then i will publish it.

Windows:
`%appdata%\..\Local\coc\extensions`

macOS:
not sure

Linux:
not sure
