### ISSUE TITLE
Typerror: e.forEach is not a function

### ISSUE THREAD

**Issue by rv178** [leonardssh/coc-discord-rpc#61]
I recently decided to re-install all my plugins, but coc.nvim throws the following error when coc-discord-rpc is running:

![image](https://user-images.githubusercontent.com/69449141/180603433-1921be84-a9dd-44cc-b957-a03e2efb6a65.png)

**Comment by BooleanCube** [comment]
I am getting the same error. Everytime i open up Neovim I get an error saying:

`[coc.nvim] RPC: TypeError: e.forEach is not a function`

**Comment by rv178** [comment]
Same issue here.

**Comment by xhayper** [comment]
Found a fix, Making a PR
