### ISSUE TITLE
Link to images used in the app?

### ISSUE THREAD

**Issue by rv178** [leonardssh/coc-discord-rpc#66]
Just curious, but is it possible to link the images used in this extension? like the language images, since they're pretty good!

**Comment by xhayper** [comment]
@leonardssh

**Comment by leonardssh** [comment]
Hey, all the icons used in this extension are available here: [leonardssh/vscord](https://github.com/leonardssh/vscord/tree/main/assets/icons)

**Comment by rv178** [comment]
thank you! :)
