### ISSUE TITLE
Displaying the wrong app name

### ISSUE THREAD

**Issue by djornada** [leonardssh/coc-discord-rpc#73]
### Operating system

ArcoLinux 5.17.6-arch1-1

### Neovim/Vim version

Vim 9.0.910

### CoC version

5.4.4

### Discord version

official

### Reproduce step

- Install _coc-discord-rpc_ and 
- open *Vim*

### Expected result

The app name displayed on discord be *Vim*

### Actual result

The app name displayed is *NeoVim* 
![image](https://user-images.githubusercontent.com/6035873/206768838-d5ad46ac-e7b3-4e39-880b-6c47fc8b6a8c.png)

**Comment by leonardssh** [comment]
That name comes from the discord application itself
![image](https://user-images.githubusercontent.com/35312043/206778823-4bad33b8-89ea-48d6-b0b0-24c91e43bd60.png)

**Comment by djornada** [comment]
@leonardssh  So if it's does not reconize Vim why exists [this]() line? And where is located this image, could you share the linkz plz?
