### ISSUE TITLE
Neovim is not NeoVim

### ISSUE THREAD

**Issue by sevenc-nanashi** [leonardssh/coc-discord-rpc#74]
### Operating system

Windows 10

### Neovim/Vim version

Neovim 0.8.1

### CoC version

0.0.82

### Discord version

official

### Reproduce step

1. Launch neovim
2. Check discord status

### Expected result

Application name is Neo**v**im

### Actual result

Application name is Neo**V**im

**Comment by xhayper** [comment]
@leonardssh

**Comment by xhayper** [comment]
wait now i am confused, NeoVim
V should be capitalized.

**Comment by leonardssh** [comment]
Fixed, now the application name should be Neovim.
